apiVersion: v1
kind: Service
metadata:
  name: ct-api-service
  namespace: command-center
  labels:
    app: command-center
    component: ct-api
    tier: api
spec:
  selector:
    app: command-center
    component: ct-api
    tier: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
